POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "react",
  "author": "lol",
  "url": "https://fullstackopen.com/",
  "likes": 4
}

###
DELETE http://localhost:3003/api/blogs/6273f06ee9e401562ccd6c98
Accept: application/json
###
PUT http://localhost:3003/api/blogs/645f56c824ed2278600cba83
Content-Type: application/json

{
  "title": "react",
  "author": "lol",
  "url": "https://fullstackopen.com/",
  "likes": 10
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "salainen"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "ansha",
  "name": "Anna Sha",
  "password": "aaaaaaaa"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "js +++",
  "author": "Anna",
  "url": "https://fullstackopen.com/",
  "likes": 5,
  "userId": "645f89449b7cd8ee39fd2527"
}
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
"username": "ansha",
"password": "aaaaaaaa",
  "passwordHash": "648c51ff5cf9a40271d3b393"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "salainen"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuc2hhIiwiaWQiOiI2NDVmODk0NDliN2NkOGVlMzlmZDI1MjciLCJpYXQiOjE2ODU1MjkyNjJ9.oGcGmPbPyrZjoD4EabKbvnyz3T35MwN_42DA1gGaLEs

{
  "title": "react is good",
  "author": "lol",
  "url": "https://fullstackopen.com/",
  "likes": 1,
  "userId": "645f89449b7cd8ee39fd2527"
}
###


###
PUT http://localhost:3003/api/blogs/647729e2680f290dcd6ae3db
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuc2hhIiwiaWQiOiI2NDVmODk0NDliN2NkOGVlMzlmZDI1MjciLCJpYXQiOjE2ODU1MjkyNjJ9.oGcGmPbPyrZjoD4EabKbvnyz3T35MwN_42DA1gGaLEs

{
  "title": "css",
  "author": "rom",
  "url": "https://fullstackopen.com/",
  "likes": 1,
  "userId": "645f89449b7cd8ee39fd2527"
}

###
PUT http://localhost:3003/api/blogs/6477236ea73ce88074138946
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuc2hhIiwiaWQiOiI2NDVmODk0NDliN2NkOGVlMzlmZDI1MjciLCJpYXQiOjE2ODU1MjkyNjJ9.oGcGmPbPyrZjoD4EabKbvnyz3T35MwN_42DA1gGaLEs

{
  "title": "react is good",
  "author": "lol",
  "url": "https://fullstackopen.com/",
  "likes": 2,
  "userId": "645f89449b7cd8ee39fd2527"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuc2hhIiwiaWQiOiI2NDVmODk0NDliN2NkOGVlMzlmZDI1MjciLCJpYXQiOjE2ODU1MjkyNjJ9.oGcGmPbPyrZjoD4EabKbvnyz3T35MwN_42DA1gGaLEs

{
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
 "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": 1,
  "userId": "648c51ff5cf9a40271d3b393"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": 1,
  "userId": "64ee114ca331a780756a1907"
}
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "rrrrrrrr"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ZWUxMzU0YTMzMWE3ODA3NTZhMTkxMSIsImlhdCI6MTY5MzQxMDg0Nn0.DwzFyziebbUYtHNBlSuIOzTbhSa2-1ywKJA89RiHOCY

{
"title": "Go To Statement Considered Harmful",
"author": "Edsger W. Dijkstra",
"url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
"likes": 1,
"userId": "64ee1354a331a780756a1911"
}